### ISSUE TITLE
augment your collection of postcodes

### ISSUE THREAD

**Issue by kapouer** [melwynfurtado/postcode-validator#1]
http://stackoverflow.com/questions/578406/what-is-the-ultimate-postal-code-and-zip-regex

has amazing links to global information about postcodes

**Comment by kapouer** [comment]
and in particular i'd choose http://unicode.org/cldr/trac/browser/trunk/common/supplemental/postalCodeData.xml

**Comment by melwynfurtado** [comment]
@kapouer Sorry for not getting back earlier. I have bumped the version to ```1.2.0``` which includes most of reg expressions in one of your links. Thanks for raising this.

**Comment by melwynfurtado** [comment]
Closing as addressed in version ```1.2.0``.
