### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by gggritso** [melwynfurtado/postcode-validator#12]
👋🏻 sorry to keep bugging you, but would you mind releasing `v1.2.1` on NPM? #11 fixes a noticeable UI annoyance that I’d like to squash

**Comment by melwynfurtado** [comment]
No worries, I'll do it tomorrow.

**Comment by melwynfurtado** [comment]
Released - https://www.npmjs.com/package/postcode-validator/v/1.2.1
