### ISSUE TITLE
Dutch postal code is quite strict

### ISSUE THREAD

**Issue by the-missing-pink** [melwynfurtado/postcode-validator#120]
The regex for the dutch postal code is quite strict. It can only have the postal code version 1111 AA.
But it can also be written as 1111aa or 1111AA.

So it is better to use somewhat of this regex.
https://rgxdb.com/r/4W9GV8AC

**Comment by melwynfurtado** [comment]
Check my comments on your pr - https://github.com/melwynfurtado/postcode-validator/pull/121
