### ISSUE TITLE
Regex for Nicaraguan postal codes is incorrect

### ISSUE THREAD

**Issue by nielslange** [melwynfurtado/postcode-validator#131]
Nicaragua uses the [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) country code `NI`. The current regex for Nicaraguan postal codes is hosted on [this GitHub repository](https://github.com/melwynfurtado/postcode-validator/blob/590e9448cea9629200ac3f0189f2c588d1508ee4/src/postcode-regexes.ts#L98C30-L98C30):

```
/^((\d{4}-)?\d{3}-\d{3}(-\d{1})?)?$/
```

This pattern successfully validates:

- An empty string → Entire pattern is optional.
- `123-456` → Core 3-3 pattern.
- `1234-123-456` → Optional 4-digit prefix.
- `123-456-7` → Optional single-digit suffix.
- `1234-123-456-7` → Includes all optional parts.

However, according to [codigo-postal.org](https://codigo-postal.org/en-us/nicaragua/zip/13024/) and [en.youbianku.com](https://en.youbianku.com/Nicaragua), Nicaraguan postal codes consist of 5 digits and never start with 0. [grcdi.nl](https://www.grcdi.nl/gsb/nicaragua.html) outlines the following specific number ranges for postal codes:

> 10-16, 21-22, 25-27, 31-32, 34-35, 37-38, 41-48, 51-52, 55-56, 61-62, 65-66, 71-72, 81-82, 91-92

And suggests this regex:

```
\A((10|11|12|13|14|15|16|21|22|25|26|27|31|32|34|35|37|38|41|42|43|44|45|46|47|48|51|52|55|56|61|62|65|66|71|72|81|82|91|92)\d{3,3})\Z
```

I recommend updating the Nicaraguan postal code regex for more accurate validation.

**Comment by melwynfurtado** [comment]
Thanks for researching Nicaraguan postcodes. Can you optimise your regex for the first two digits as I see the first digit can be 1-9 and the second digit 1-7?
