### ISSUE TITLE
UK is not a valid country code

### ISSUE THREAD

**Issue by lukehaas** [melwynfurtado/postcode-validator#25]
The available country codes seem to be following the ISO 3166-1 standard, with the exception of 'UK' this is not a valid country code, it should be 'GB'.

A full list of  ISO 3166-1 country codes can be found here: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by melwynfurtado** [comment]
Thanks @lukehaas, please open a PR to correct this and keep `UK` too for backward compatibility else it will need to be released in major version.

**Comment by melwynfurtado** [comment]
Merged as part of https://github.com/melwynfurtado/postcode-validator/pull/38/files
