### ISSUE TITLE
Fall back to INTL on Country Mismatch?

### ISSUE THREAD

**Issue by bitbutcher** [melwynfurtado/postcode-validator#4]
Firstly, thank you for taking the time to research, implement and share this library.  I can see it being useful for a very large number of use cases.

Unfortunatley, the hidden fallback behavior expressed by:

```
  for (reKey in regexes) {
    if (regexes[reKey].test(code)) { return true }
  }
```

Seems:

1) Far more lenient than what is implied by the external API.  If I specify a country code in the function call the API strongly implies I'm asking "Is this a valid postal code for the given country?"  But the implementation results in "Is this a valid postal code for planet earth?"

2) Potentially very inefficient.  Since a miss in the set check that occurs above this code typically indicates I've specified a valid country code that has yet to be implemented I'm very likely to iterate all the way through to `INTL`.  Given that Regex isn't the most performant activity in the world this could represent a pretty harsh waste of time and resources.

Depending on the client I could see them desiring 1 of 3 behaviors (with 1 and 2 likely being far more popular due to the reasoning from above):

1) Strict validation with no fallback at all.
2) Lenient validation that tries the specified country code and falls back to INTL if that country is not yet implemented.
3) The current behavior

Perhaps the lib publishes a builder function that allows the client to configure the behavior they desire, or the currently published function accepts an optional third argument that accomplishes the same thing, but must be passed on each invocation.

**Comment by edargelies** [comment]
Hi, this is probably stale by now, but I had the same thoughts and implemented what you asked for in my fork. https://github.com/edargelies/postcode-validator Hope it can help you!

**Comment by melwynfurtado** [comment]
Thanks @bitbutcher. I think the behaviour should be to error out on invalid country code. I think using lenient validation may still result in false positives for some use cases when client accidentally passes incorrect country code and it falls back to international and passes/fails.

@edargelies Let me know if you can make amends to your PR https://github.com/melwynfurtado/postcode-validator/pull/5 to do strict validation. Thanks.

**Comment by edargelies** [comment]
@melwynfurtado by all means, feel free to amend it. Thanks again for this utility!

**Comment by melwynfurtado** [comment]
@edargelies Ok, PR https://github.com/melwynfurtado/postcode-validator/pull/14 created/merged.
