### ISSUE TITLE
MU postal code regex is incorrect

### ISSUE THREAD

**Issue by james-braund-gw** [melwynfurtado/postcode-validator#47]
Good morning,

It appears that the regex pattern for Mauritius (MU) postal codes is incorrect.

The format should allow for either a letter and 4 digits, or 5 digits. At present, it instead expects a 111AA111 pattern.

Sources:
https://en.wikipedia.org/wiki/Postal_codes_in_Mauritius
https://www.mauritiuspost.mu/products-and-services/post-and-zip-code-finder

Suggested regex to fix this:

```
[CountryCode.MU, /^((\d|[A-Z])\d{4})?$/]
```

You could make this stricter, and enforce a prefix of either 1-9 or the letters A/R, but this might not be particularly future-proof if the range gets expanded.

Cheers,
James

**Comment by melwynfurtado** [comment]
@james-braund-gw  thanks for raising this issue, please feel free to raise a PR to correct this.
