### ISSUE TITLE
Accepts invalid UK Postcodes 

### ISSUE THREAD

**Issue by bramfitt** [melwynfurtado/postcode-validator#8]
Valid UK Postcodes are in the format
AA9A 9AA	
A9A 9AA	
A9 9AA	
A99 9AA	
AA9 9AA	
AA99 9AA

Note the space 

I think you need the following regex 

^([A-Z]){1}([0-9][0-9]|[0-9]|[A-Z][0-9][A-Z]|[A-Z][0-9][0-9]|[A-Z][0-9]|[0-9][A-Z]){1}([ ])([0-9][A-z][A-z]){1}$

**Comment by melwynfurtado** [comment]
@bramfitt do you mind opening a PR and I can merge and release new version ?

**Comment by melwynfurtado** [comment]
Further details on this issue status is at https://github.com/melwynfurtado/postcode-validator/pull/10
